---
- name: Deploy xyz-application to k8s cluster
  hosts: k8s
  remote_user: ubuntu
  tasks:
  - name: copy deployment.yaml file to target machine
    copy:
      src: deployment.yaml
      dest: /home/ubuntu/deployment-xyz-application.yaml
      owner: ubuntu
      group: ubuntu
      force: yes
  - name: Apply deployment.yaml
    command: kubectl apply -f /tmp/deployment.yaml --validate=false
      
