---
- name: Build and Push Docker Image to DockerHub
  hosts: localhost
  vars:
    docker_image_name: "xyz-repo-application"
    docker_image_tag: "{{ lookup('env', 'BUILD_NUMBER') }}"
  vars_files:
    - secrets.yaml

  tasks:
    - name: Log in to dockerhub
      command: docker login --username {{ docker_hub_username }} --password {{ docker_hub_password }}

    - name: Tag the docker image for dockerhub
      command: docker tag {{ docker_image_name }}:{{ docker_image_tag }} {{ docker_hub_username }}/{{ docker_image_name }}:{{ docker_image_tag }}

    - name: Push the docker image to dockerhub
      command: docker push {{ docker_hub_username }}/{{ docker_image_name }}:{{ docker_image_tag }}