apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-application-deployment
  labels:
    app: xyz-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: xyz-service
  template:
    metadata:
      labels:
        app: xyz-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9100"
    spec:
      containers:
        - name: xyz-application-service-container
          image: kkpdealwis93/xyz-repo-application:BUILD_NUMBER
          ports:
            - containerPort: 8080
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest
          ports:
            - containerPort: 9100
          args:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
